"""Remove is_admin and _hashed_password columns

Revision ID: 35198f1bac7f
Revises: dfee89476203
Create Date: 2024-07-20 17:41:48.301680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35198f1bac7f'
down_revision = 'dfee89476203'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_admin')
        batch_op.drop_column('_hashed_password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_hashed_password', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('is_admin', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
