"""Add password

Revision ID: 580d8543fae9
Revises: 35198f1bac7f
Create Date: 2024-07-22 22:47:52.201486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '580d8543fae9'
down_revision = '35198f1bac7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_hashed_password', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('_hashed_password')

    # ### end Alembic commands ###
